# CMake generated Testfile for 
# Source directory: /Users/aditya/ns-allinone-3.38/ns-3.38/scratch
# Build directory: /Users/aditya/ns-allinone-3.38/ns-3.38/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_diff_serv "ns3.38-diff_serv-debug")
set_tests_properties(ctest-scratch_diff_serv PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_filter "ns3.38-filter-debug")
set_tests_properties(ctest-scratch_filter PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_filter_elements "ns3.38-filter_elements-debug")
set_tests_properties(ctest-scratch_filter_elements PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_lab32 "ns3.38-lab32-debug")
set_tests_properties(ctest-scratch_lab32 PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.38-scratch-simulator-debug")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_simple-udp-echo "ns3.38-simple-udp-echo-debug")
set_tests_properties(ctest-scratch_simple-udp-echo PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_spq "ns3.38-spq-debug")
set_tests_properties(ctest-scratch_spq PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_starter "ns3.38-starter-debug")
set_tests_properties(ctest-scratch_starter PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_traffic_class "ns3.38-traffic_class-debug")
set_tests_properties(ctest-scratch_traffic_class PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;59;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.38-scratch-subdir-debug")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/scratch/subdir/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;47;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;89;create_scratch;/Users/aditya/ns-allinone-3.38/ns-3.38/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
