# CMake generated Testfile for 
# Source directory: /Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples
# Build directory: /Users/aditya/ns-allinone-3.38/ns-3.38/cmake-cache/src/nix-vector-routing/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-nix-simple "ns3.38-nix-simple-debug")
set_tests_properties(ctest-nix-simple PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-simple-multi-address "ns3.38-nix-simple-multi-address-debug")
set_tests_properties(ctest-nix-simple-multi-address PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nms-p2p-nix "ns3.38-nms-p2p-nix-debug")
set_tests_properties(ctest-nms-p2p-nix PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-double-wifi "ns3.38-nix-double-wifi-debug")
set_tests_properties(ctest-nix-double-wifi PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;22;build_lib_example;/Users/aditya/ns-allinone-3.38/ns-3.38/src/nix-vector-routing/examples/CMakeLists.txt;0;")
