# CMake generated Testfile for 
# Source directory: /Users/aditya/ns-allinone-3.38/ns-3.38/src/internet/examples
# Build directory: /Users/aditya/ns-allinone-3.38/ns-3.38/cmake-cache/src/internet/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-main-simple "ns3.38-main-simple-debug")
set_tests_properties(ctest-main-simple PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/src/internet/examples/CMakeLists.txt;1;build_lib_example;/Users/aditya/ns-allinone-3.38/ns-3.38/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-example "ns3.38-neighbor-cache-example-debug")
set_tests_properties(ctest-neighbor-cache-example PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/src/internet/examples/CMakeLists.txt;10;build_lib_example;/Users/aditya/ns-allinone-3.38/ns-3.38/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-dynamic "ns3.38-neighbor-cache-dynamic-debug")
set_tests_properties(ctest-neighbor-cache-dynamic PROPERTIES  WORKING_DIRECTORY "/Users/aditya/ns-allinone-3.38/ns-3.38/build/src/internet/examples/" _BACKTRACE_TRIPLES "/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1545;add_test;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/macros-and-definitions.cmake;1617;set_runtime_outputdirectory;/Users/aditya/ns-allinone-3.38/ns-3.38/build-support/custom-modules/ns3-module-macros.cmake;414;build_exec;/Users/aditya/ns-allinone-3.38/ns-3.38/src/internet/examples/CMakeLists.txt;20;build_lib_example;/Users/aditya/ns-allinone-3.38/ns-3.38/src/internet/examples/CMakeLists.txt;0;")
